sudo: true

language: python

python: 3.7

cache:
    - pip

before_install:
    - sudo apt update
    - sudo apt install -y quantum-espresso 
    - pip install codecov pytest pytest-cov pytest_mock
    - pwd
    - wget http://folk.uio.no/anjohan/lmp
    - "wget https://github.com/cp2k/cp2k/releases/download/\
      v7.1.0/cp2k-7.1-Linux-x86_64.sopt"
    - chmod u+x lmp
    - chmod u+x cp2k-7.1-Linux-x86_64.sopt
    - pip install .

script:
    - pwd
    - ls
    - cd flare
    - ls
    - cd ..
    - cd tests
    - ls test_files
    - PWSCF_COMMAND=pw.x
      lmp=$(pwd)/../lmp
      CP2K_COMMAND=../cp2k-7.1-Linux-x86_64.sopt
      pytest -vv --durations=0 --cov=../flare/
    - coverage xml

after_success:
    - codecov
